### ISSUE TITLE
Use ISO date time format

### ISSUE THREAD

**Issue by gbenziv** [pointonsoftware/pscore#238]
Replace 

`YYYY/MM/DD hh:mm:ss`

with

`YYYY-MM-DD hh:mm:ss`

**Comment by gbenziv** [comment]
areas:

utility/datetime
orchestra/migration/storage/stackdb.cpp
validator/personvalidator
validator/uservalidator
screens/customermgmtscreen
screens/empmgmtscreen

**Comment by alimustafashah** [comment]
Can you assign this task to me?
