### ISSUE TITLE
Console app exits when any string with letter "x" is inputted

### ISSUE THREAD

**Issue by gbenziv** [pointonsoftware/pscore#69]
Steps to reproduce:
1) Run console app
2) In the PIN input field, type any word with "x". e.g. "fax"

EXPECTATION

- Console app should return error saying "Invalid PIN"

ACTUAL

- Console app exits

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me

**Comment by gbenziv** [comment]
Fixed with #100
